### ISSUE TITLE
Erro 404 ao deletar aula dia 3

### ISSUE THREAD

**Issue by EdisonLemesSantos** [gabriel-paiva/semana-omnistack-11#2]
Não consigo encontrar o erro. Já revisei o código e não faço ideia do que esta ocorrendo.
Se alguém sou ber como resolver? Por favor responda.

**Comment by httpaiva** [comment]
Poderia mandar print do erro e da parte do código que ele referencia?

**Comment by EdisonLemesSantos** [comment]
Não mostra mais nada, além do erro 404.
![erro-404](https://user-images.githubusercontent.com/62606574/80615224-c7d82900-8a15-11ea-8a9e-7f7af21ebf20.jpg)

**Comment by httpaiva** [comment]
Pode mostrar também a listagem de incidentes?

**Comment by EdisonLemesSantos** [comment]
Eu deletei o banco  recriei para ver se resolvia mas não resolveu.
![erro-lista-404](https://user-images.githubusercontent.com/62606574/80626507-f0b3ea80-8a24-11ea-9614-ec0e17f9003c.jpg)

**Comment by httpaiva** [comment]
Cara, acredito que esse erro ao deletar os itens esteja acontecendo porque há um erro de digitação no seu routes.js
No seu arquivo, está escrito assim:
"routes.delete('**/icidents**/:id', IncidentController.delete);"
O certo seria:
"routes.delete('/**incidents**/:id', IncidentController.delete);"
Atualmente, como não existe rota para "incidents", ele não consegue achar o item a ser deletado e dá esse 404.

**Comment by EdisonLemesSantos** [comment]
Eu encontrei o erro. Estava na rotas, a ordem das conexões. Encontrei um código onde usei para revisar o meu, encontrei e corrigi. Funcionou corretamente. Obrigado pela ajuda. Depois eu posto a imagem corrigida.

**Comment by httpaiva** [comment]
Boa, cara!

**Comment by EdisonLemesSantos** [comment]
Aqui estão os erros que eu encontrei. Acho que teve outros, mas eu resolvi com control+c e control+v, para ir mais rápido.
![erro-encontrado](https://user-images.githubusercontent.com/62606574/80975332-596ddf00-8df8-11ea-91e1-940bfb2366fb.jpg)
![erro2-encontrado](https://user-images.githubusercontent.com/62606574/80975348-5ecb2980-8df8-11ea-9882-357246d8b74c.jpg)
